name: Test and Release

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm ci
          npm install --global @salesforce/cli
      - name: Run unit tests
        run: npm run test
      - name: Authenticate DevHub and create scratch org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --alias devhub --sfdx-url-stdin
          npm run develop
      - name: Run end-to-end tests
        run: npm run test:e2e
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch --no-prompt
  release:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Release package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
